version: '3.8'

services:
  graph:
    image: zepai/graphiti:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/healthcheck')" ]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEO4J_URI=bolt://10.0.0.4:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=e5tWkrr6.Q+e
      - PORT=8000

volumes:
  neo4j_data:
